name: CD for RegisterBus

on:
  workflow_dispatch: # Necesario para que sea ejecutado manualmente o desde otro workflow
    inputs:
      branch:
        description: 'Branch to build'
        required: true
        default: 'dev'

permissions:
  contents: write

  push:
    branches: ["dev"]

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and push Docker image for RegisterBus
        run: |
          echo "Building Docker image for ${{ github.event.inputs.service }}"
          # Aquí va tu script personalizado
