services:
  delete-route:
    build:
      context: ./DeleteRoute
      dockerfile: Dockerfile
    image: "${DOCKER_USERNAME}/${DOCKER_REPOSITORY_NAME_ROUTE_DELETE}:latest"
    restart: always

  list-route:
    build:
      context: ./ListRoute
      dockerfile: Dockerfile
    image: "${DOCKER_USERNAME}/${DOCKER_REPOSITORY_NAME_ROUTE_LIST}:latest"
    restart: always

  register-route:
    build:
      context: ./RegisterRoute
      dockerfile: Dockerfile
    image: "${DOCKER_USERNAME}/${DOCKER_REPOSITORY_NAME_ROUTE_REGISTER}:latest"
    restart: always

  update-route:
    build:
      context: ./UpdateRoute
      dockerfile: Dockerfile
    image: "${DOCKER_USERNAME}/${DOCKER_REPOSITORY_NAME_ROUTE_UPDATE}:latest"
    restart: always