version: "3.8"  # Especifica la versión de Docker Compose (puedes ajustarla si es necesario)

services:
  delete-route:
    build:
      context: ./DeleteRoute
      dockerfile: Dockerfile
    image: "${DOCKER_USERNAME}/${DOCKER_REPOSITORY_NAME_ROUTE_DELETE}:latest"
    restart: always
    ports:
      - "3001:3001"  # Puerto para el servicio delete-route (puedes cambiarlo)
    depends_on:
      - mongodb  # Dependencia del servicio de MongoDB
    environment:
      - MONGODB_URI=mongodb://${MONGODB_USER}:${MONGODB_PASSWORD}@${MONGODB_HOST}:${MONGODB_PORT}/${MONGODB_DATABASE}
      # Otras variables de entorno que necesites

  list-route:
    build:
      context: ./ListRoute
      dockerfile: Dockerfile
    image: "${DOCKER_USERNAME}/${DOCKER_REPOSITORY_NAME_ROUTE_LIST}:latest"
    restart: always
    ports:
      - "3002:3002"  # Puerto para el servicio list-route (puedes cambiarlo)
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://${MONGODB_USER}:${MONGODB_PASSWORD}@${MONGODB_HOST}:${MONGODB_PORT}/${MONGODB_DATABASE}
      # Otras variables de entorno

  register-route:
    build:
      context: ./RegisterRoute
      dockerfile: Dockerfile
    image: "${DOCKER_USERNAME}/${DOCKER_REPOSITORY_NAME_ROUTE_REGISTER}:latest"
    restart: always
    ports:
      - "3003:3003"  # Puerto para el servicio register-route (puedes cambiarlo)
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://${MONGODB_USER}:${MONGODB_PASSWORD}@${MONGODB_HOST}:${MONGODB_PORT}/${MONGODB_DATABASE}
      # Otras variables de entorno

  update-route:
    build:
      context: ./UpdateRoute
      dockerfile: Dockerfile
    image: "${DOCKER_USERNAME}/${DOCKER_REPOSITORY_NAME_ROUTE_UPDATE}:latest"
    restart: always
    ports:
      - "3004:3004"  # Puerto para el servicio update-route (puedes cambiarlo)
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://${MONGODB_USER}:${MONGODB_PASSWORD}@${MONGODB_HOST}:${MONGODB_PORT}/${MONGODB_DATABASE}
      # Otras variables de entorno

  mongodb:  # Servicio de MongoDB
    image: mongo:latest  # o la versión que prefieras
    restart: always
    environment:
      - MONGODB_USER=${MONGODB_USER}  # Usuario para la aplicación
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}  # Contraseña para la aplicación
      - MONGODB_DATABASE=${MONGODB_DATABASE}  # Nombre de la base de datos
    ports:
      - "27017:27017"  # Publica el puerto solo si necesitas acceder desde tu máquina local (opcional)
    volumes:
      - mongodb_data:/data/db  # Persiste los datos de MongoDB

volumes:
  mongodb_data:  # Volumen para los datos de MongoDB