services:
  delete-user:
    build:
      context: ./DeleteUser
      dockerfile: Dockerfile
    image: "${DOCKER_USERNAME}/${DOCKER_REPOSITORY_NAME_USER_DELETE}:latest"
    restart: always
    depends_on:
      - postgres
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
    ports:
      - "2004:2004"

  list-user:
    build:
      context: ./ListUser
      dockerfile: Dockerfile
    image: "${DOCKER_USERNAME}/${DOCKER_REPOSITORY_NAME_USER_LIST}:latest"
    restart: always
    depends_on:
      - postgres
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
    ports:
      - "2002:2002"

  login-user:
    build:
      context: ./LoginUser
      dockerfile: Dockerfile
    image: "${DOCKER_USERNAME}/${DOCKER_REPOSITORY_NAME_USER_LOGIN}:latest"
    restart: always
    depends_on:
      - postgres
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
    ports:
      - "2001:2001"

  register-user:
    build:
      context: ./RegisterUser
      dockerfile: Dockerfile
    image: "${DOCKER_USERNAME}/${DOCKER_REPOSITORY_NAME_USER_REGISTER}:latest"
    restart: always
    depends_on:
      - postgres
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
    ports:
      - "2000:2000"

  update-user:
    build:
      context: ./UpdateUser
      dockerfile: Dockerfile
    image: "${DOCKER_USERNAME}/${DOCKER_REPOSITORY_NAME_USER_UPDATE}:latest"
    restart: always
    depends_on:
      - postgres
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
    ports:
      - "2003:2003"

  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
