
services:
  register-bus:
    build:
      context: ./RegisterBus
      dockerfile: Dockerfile
    image: "${DOCKER_USERNAME}/${DOCKER_REPOSITORY_NAME_REGISTERBUS}:latest"
    restart: always
    volumes:
      - ./RegisterBus:/app

  delete-bus:
    build:
      context: ./DeleteBus
      dockerfile: Dockerfile
    image: "${DOCKER_USERNAME}/${DOCKER_REPOSITORY_NAME_DELETEBUS}:latest"
    restart: always

  update-bus:
    build:
      context: ./UpdateBusAvailability
      dockerfile: Dockerfile
    image: "${DOCKER_USERNAME}/${DOCKER_REPOSITORY_NAME_BUS_UPDATE}:latest"
    restart: always

  view-bus:
    build:
      context: ./ViewBusDetails
      dockerfile: Dockerfile
    image: "${DOCKER_USERNAME}/${DOCKER_REPOSITORY_NAME_BUS_VIEW}:latest"
    restart: always
