name: Login to Docker Hub and push new image version

on:
  workflow_call:
    secrets:
      docker_username:
        required: true
      docker_password:
        required: true
      repository_name_availability_ticket:
        required: true
      repository_name_delete_ticket:
        required: true
      repository_name_register_ticket:
        required: true
      repository_name_update_ticket:
        required: true
      repository_name_view_ticket:
        required: true

jobs:
  login_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.docker_password }}" | docker login -u "${{ secrets.docker_username }}" --password-stdin

      - name: Build and push images with Docker Compose
        run: |
          export DOCKER_USERNAME="${{ secrets.docker_username }}"
          export DOCKER_REPOSITORY_NAME_TICKET_AVAILABILITY="${{ secrets.repository_name_availability_ticket }}"
          export DOCKER_REPOSITORY_NAME_TICKET_DELETE="${{ secrets.repository_name_delete_ticket }}"
          export DOCKER_REPOSITORY_NAME_TICKET_REGISTER="${{ secrets.repository_name_register_ticket }}"
          export DOCKER_REPOSITORY_NAME_TICKET_UPDATE="${{ secrets.repository_name_update_ticket }}"
          export DOCKER_REPOSITORY_NAME_TICKET_VIEW="${{ secrets.repository_name_view_ticket }}"

          docker-compose -f ./TicketManagement/docker-compose.yml build
          docker-compose -f ./TicketManagement/docker-compose.yml push