name: Login to Docker Hub and push new image version

on:
  workflow_call:
    secrets:
      docker_username:
        required: true
      docker_password:
        required: true
      repository_name_login_user:
        required: true
      repository_name_delete_user:
        required: true
      repository_name_list_user:
        required: true
      repository_name_register_user:
        required: true
      repository_name_update_user:
        required: true
      repository_name_view_user:
        required: true


jobs:
  login_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.docker_password }}" | docker login -u "${{ secrets.docker_username }}" --password-stdin

      - name: Build and push images with Docker Compose
        run: |
          export DOCKER_USERNAME="${{ secrets.docker_username }}"
          export DOCKER_REPOSITORY_NAME_USER_LOGIN="${{ secrets.repository_name_login_user }}"
          export DOCKER_REPOSITORY_NAME_USER_DELETE="${{ secrets.repository_name_delete_user }}"
          export DOCKER_REPOSITORY_NAME_USER_LIST="${{ secrets.repository_name_list_user }}"
          export DOCKER_REPOSITORY_NAME_USER_REGISTER="${{ secrets.repository_name_register_user }}"
          export DOCKER_REPOSITORY_NAME_USER_UPDATE="${{ secrets.repository_name_update_user }}"
          export DOCKER_REPOSITORY_NAME_USER_VIEW="${{ secrets.repository_name_view_user }}"

          docker-compose -f ./UserManagement/docker-compose.yml build
          docker-compose -f ./UserManagement/docker-compose.yml push