name: Login to Docker Hub and push new image version

on:
  workflow_call:
    secrets:
      docker_username:
        required: true
      docker_password:
        required: true
      repository_name_delete_payment:
        required: true
      repository_name_list_payment:
        required: true
      repository_name_register_payment:
        required: true
      repository_name_update_payment:
        required: trueS

jobs:
  login_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.docker_password }}" | docker login -u "${{ secrets.docker_username }}" --password-stdin

      - name: Build and push images with Docker Compose
        run: |
          export DOCKER_USERNAME="${{ secrets.docker_username }}"
          export DOCKER_REPOSITORY_NAME_PAYMENT_DELETE="${{ secrets.repository_name_delete_payment }}"
          export DOCKER_REPOSITORY_NAME_PAYMENT_LIST="${{ secrets.repository_name_list_payment }}"
          export DOCKER_REPOSITORY_NAME_PAYMENT_REGISTER="${{ secrets.repository_name_register_payment }}"
          export DOCKER_REPOSITORY_NAME_PAYMENT_UPDATE="${{ secrets.repository_name_update_payment }}"

          docker-compose -f ./PaymentManagement/docker-compose.yml build
          docker-compose -f ./PaymentManagement/docker-compose.yml push