name: Registry image

on:
  push:
    branches: ["dev"]

jobs:
  login-push-bus-update:
    uses: ./.github/workflows/login_pull.yml
    secrets:
      docker_password: ${{ secrets.DOCKER_PASSWORD }}
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      repository_name: ${{ secrets.DOCKER_REPOSITORY_NAME_BUS_UPDATE }}

