name: EC2 deploy from docker

on:
  push:
    branches: ["dev"]

jobs:
  Deploy-Docker-Compose-Bus-Management:
    uses: ./.github/workflows/login_pull.yml
    secrets:
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      docker_password: ${{ secrets.DOCKER_PASSWORD }}
      repository_name_registerbus: ${{ secrets.DOCKER_REPOSITORY_NAME_REGISTERBUS }}
      repository_name_deletebus: ${{ secrets.DOCKER_REPOSITORY_NAME_DELETEBUS }}
      repository_name_update_bus: ${{ secrets.DOCKER_REPOSITORY_NAME_BUS_UPDATE }}
      repository_name_view_bus: ${{ secrets.DOCKER_REPOSITORY_NAME_BUS_VIEW }}

  Deploy-Docker-Compose-Notification-Management:
    uses: ./.github/workflows/login_pull.yml
    secrets:
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      docker_password: ${{ secrets.DOCKER_PASSWORD }}
      repository_name_notification_create: ${{ secrets.DOCKER_REPOSITORY_NAME_NOTIFICATION_CREATE }}
      repository_name_notification_delete: ${{ secrets.DOCKER_REPOSITORY_NAME_NOTIFICATION_DELETE }}
      repository_name_notification_view: ${{ secrets.DOCKER_REPOSITORY_NAME_NOTIFICATION_VIEW }}


  ssh-connect-ec2-Bus-Management:
      needs: Deploy-Docker-Compose-Bus-Management
      uses: ./.github/workflows/startEC2.yml
      secrets:
        ec2_host: ${{ secrets.EC2_HOST_BUS_MANAGEMENT }}
        ec2_key: ${{ secrets.EC2_KEY_BUS_MANAGEMENT }}
        docker_username: ${{ secrets.DOCKER_USERNAME }}