name: Register Bus # Nombre del workflow (puede ser diferente al nombre del archivo)
on:
  workflow_call:
    inputs:
      docker_repo_name: # Input para el nombre del repositorio
        required: true
        type: string
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code # Descarga el código del repositorio
        uses: actions/checkout@v3

      - name: Login to Docker Hub # Inicia sesión en Docker Hub (o tu registro)
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image # Construye y sube la imagen Docker
        run: |
          REPO_NAME="${{ inputs.docker_repo_name }}" # Obtiene el nombre del repositorio del input

          # Validación del nombre del repositorio (opcional, pero recomendada)
          if [[ ! "$REPO_NAME" =~ ^[a-zA-Z0-9._-]+$ ]]; then
            echo "ERROR: Invalid repository name. Must contain only alphanumeric characters, periods, underscores, or hyphens."
            exit 1
          fi

          DOCKERFILE_PATH="./BusManagement/RegisterBus/Dockerfile" # Ruta al Dockerfile
          CONTEXT_PATH="./BusManagement/RegisterBus" # Ruta al contexto de construcción

          docker buildx build --platform linux/amd64 --build-arg BUILDKIT_INLINE_CACHE=1 -f "$DOCKERFILE_PATH" -t "${{ secrets.DOCKER_USERNAME }}/$REPO_NAME:latest" "$CONTEXT_PATH" --push