name: Delete Bus
on:
  workflow_call:
    secrets:
      docker_repo_name:
        required: true
      docker_username:
        required: true
      docker_password:
        required: true

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and push Docker image
        run: |
          echo "${{ secrets.docker_password }}" | docker login -u "${{ secrets.docker_username }}" --password-stdin
          REPO_NAME="${{ inputs.docker_repo_name }}"
          echo "Repo name: $REPO_NAME"
          if [[ ! "$REPO_NAME" =~ ^[a-zA-Z0-9._-]+$ ]]; then
            echo "ERROR: Invalid repository name."
            exit 1
          fi
          DOCKERFILE_PATH="./BusManagement/RegisterBus/Dockerfile"
          CONTEXT_PATH="./BusManagement/RegisterBus"
          docker buildx build --platform linux/amd64 --build-arg BUILDKIT_INLINE_CACHE=1 -f "$DOCKERFILE_PATH" -t "${{ secrets.DOCKER_USERNAME }}/$REPO_NAME:latest" "$CONTEXT_PATH" --push
