name: Main Workflow
on:
  push:
    branches: [dev]

jobs:
  manage_buses:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Register Bus
        uses: ./.github/workflows/bus-management/Register-Bus.yml # Ruta RELATIVA CORRECTA

      - name: Delete Bus
        uses: ./.github/workflows/bus-management/Delete-Bus.yml # Ruta RELATIVA CORRECTA

      - name: Update Bus Availability
        uses: ./.github/workflows/bus-management/Update-Bus-Availability.yml # Ruta RELATIVA CORRECTA