name: Registry image

on:
  push:
    branches: ["dev"]

permissions:
  contents: write
  actions: write # Necesario para ejecutar otros workflows

jobs:
  trigger-registerbus:
    name: Trigger RegisterBus workflow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Trigger RegisterBus workflow
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Triggering RegisterBus workflow"
          gh workflow run cd.yml \
            -R ${{ github.repository }} \
            -f branch=dev
