name: Docker Setup & Update & Run new images

on:
  workflow_call:
    secrets:
      docker_username:
        required: true
      ec2_host:
        required: true
      ec2_key:
        required: true


jobs:
  connect_update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create private key file
        run: |
          echo "${{ secrets.ec2_key }}" > private_key.pem
          chmod 400 private_key.pem

      - name: Copy docker-compose.yml from ${{ secrets.domain }} to EC2
        run: |
          rsync -avz -e "ssh -o StrictHostKeyChecking=no -i private_key.pem" BusManagement/docker-compose.yml ubuntu@${{ secrets.ec2_host }}:/home/ubuntu/BusManagement/
                
      - name: SSH into EC2 and Deploy Application
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@${{ secrets.ec2_host }} << EOF
            # Instala Docker si no está instalado
            if ! command -v docker &> /dev/null; then
              sudo apt update
              sudo apt install -y docker.io
              sudo systemctl enable docker
              sudo usermod -aG docker ubuntu
            fi

            # Instala Docker Compose correctamente en Ubuntu 24.04
            if ! command -v docker-compose &> /dev/null; then
              sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64" -o /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose
            fi

            # Verifica la instalación
            docker-compose --version

            # Ir al directorio correcto
            cd /home/ubuntu/BusManagement/

            # Ejecutar docker-compose usando el dominio dinámico
            sudo docker-compose -f /home/ubuntu/BusManagement/docker-compose.yml pull
            sudo docker-compose -f /home/ubuntu/BusManagement/docker-compose.yml down || true
            sudo docker-compose -f /home/ubuntu/BusManagement/docker-compose.yml up -d --build
          EOF
