name: Start EC2 and Deploy

on:
  workflow_call:
    secrets:

      ec2_host:
        required: true
      ec2_key:
        required: true
      domain:
        required: true
      repository_name_registerbus:
        required: true
      repository_name_deletebus:
        required: true
      repository_name_update_bus:
        required: true
      repository_name_view_bus:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup SSH Key
        run: |
          echo "${{ secrets.ec2_key }}" > private_key.pem
          chmod 600 private_key.pem

      - name: SSH into EC2 and Deploy Application
        run: |
          ssh -T -o StrictHostKeyChecking=no -i private_key.pem ubuntu@${{ secrets.ec2_host }} << EOF
            export DOCKER_USERNAME="franchescoac"
            export DOCKER_REPOSITORY_NAME_REGISTERBUS="${{ secrets.repository_name_registerbus }}"
            export DOCKER_REPOSITORY_NAME_DELETEBUS="${{ secrets.repository_name_deletebus }}"
            export DOCKER_REPOSITORY_NAME_BUS_UPDATE="${{ secrets.repository_name_update_bus }}"
            export DOCKER_REPOSITORY_NAME_BUS_VIEW="${{ secrets.repository_name_view_bus }}"

            cd /home/ubuntu/${{ secrets.domain }}/
            sudo docker-compose -f /home/ubuntu/${{ secrets.domain }}/docker-compose.yml pull
            sudo docker-compose -f /home/ubuntu/${{ secrets.domain }}/docker-compose.yml down || true
            sudo docker-compose -f /home/ubuntu/${{ secrets.domain }}/docker-compose.yml up -d --build
          EOF
