name: Docker Setup & Update & Run new images

on:
  workflow_call:
    secrets:
      docker_username:
        required: true
      ec2_host:
        required: true
      ec2_key:
        required: true

jobs:
  connect_update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create private key file
        run: |
          echo "${{ secrets.ec2_key }}" > private_key.pem
          chmod 400 private_key.pem  # Permiso más seguro

      - name: Copy files to EC2 using rsync
        run: |
          rsync -avz -e "ssh -o StrictHostKeyChecking=no -i private_key.pem" . ubuntu@${{ secrets.ec2_host }}:/home/ubuntu/  # Copia todo el repo

      - name: SSH into EC2 and Deploy Application
        uses: actions/ssh@v1 # Acción oficial de GitHub
        with:
          host: ${{ secrets.ec2_host }}
          username: ubuntu
          key: ${{ secrets.ec2_key }}
          script: |
            # Instala Docker y Docker Compose (mejorado)
            if ! command -v docker &> /dev/null; then
              sudo apt update
              sudo apt install -y docker.io docker-compose-plugin
              sudo systemctl enable docker
              sudo usermod -aG docker ubuntu
              newgrp docker
            elif ! command -v docker compose &> /dev/null; then # Verifica solo docker compose
              sudo apt update
              sudo apt install -y docker-compose-plugin
            fi

            cd /home/ubuntu/  # Navega al directorio del proyecto (donde está docker-compose.yml)

            sudo docker compose pull
            sudo docker compose down || true
            sudo docker compose up -d --build