name: Docker Setup & Update Application (Reusable Workflow)

on:
  workflow_call:
    secrets:
      docker_username:
        required: true
      ec2_host:
        required: true
      ec2_key:
        required: true

jobs:
  connect_update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create private key file
        run: |
          echo "${{ secrets.ec2_key }}" > private_key.pem
          chmod 400 private_key.pem

      - name: Copy files to EC2 using rsync
        run: |
          rsync -avz -e "ssh -o StrictHostKeyChecking=no -i private_key.pem" ./ ubuntu@${{ secrets.ec2_host }}:/home/ubuntu/ 

      - name: SSH into EC2 and Deploy Application
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@${{ secrets.ec2_host }} << EOF
            # Install Docker and Docker Compose (improved)
            if ! command -v docker &> /dev/null; then
              sudo apt update
              sudo apt install -y docker.io docker-compose-plugin
              sudo systemctl enable docker
              sudo usermod -aG docker ubuntu
              newgrp docker
            elif ! command -v docker compose &> /dev/null; then # Verifica solo docker compose
              sudo apt update
              sudo apt install -y docker-compose-plugin
            fi

            # Navigate to project directory
            cd /home/ubuntu/BusManagement # Ajusta la ruta si es diferente

            # Pull images, stop old containers, and start new ones (combined)
            sudo docker compose pull
            sudo docker compose down || true
            sudo docker compose up -d --build
          EOF

      - name: Cleanup private key file
        if: always()
        run: rm -f private_key.pem