name: Docker Setup & Update Application (Reusable Workflow)

on:
  workflow_call:
    secrets:
      docker_username:
        required: true
      ec2_host:
        required: true
      ec2_key:
        required: true

jobs:
  connect_update:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Crear archivo de clave privada
      run: |
        echo "${{ secrets.ec2_key }}" > private_key.pem
        chmod 600 private_key.pem
        ls -l private_key.pem 

    - name: Copy files a EC2 usando rsync
      run: |
        rsync -avz -e "ssh -o StrictHostKeyChecking=no -i private_key.pem" ./ ubuntu@${{ secrets.ec2_host }}:/home/ubuntu/BusManagement/

    - name: SSH into EC2 and Deploy Application
      run: |
        ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@${{ secrets.ec2_host }} << 'EOF'
          # Verificar e instalar Docker
          if ! command -v docker &> /dev/null; then
            sudo apt update
            sudo apt install -y docker.io docker-compose
            sudo systemctl start docker
            sudo systemctl enable docker
            sudo usermod -aG docker ubuntu
            exec su -l ubuntu
          fi

          # Navegar al directorio del proyecto
          cd /home/ubuntu/BusManagement

          # Descargar las imágenes y reiniciar servicios
          sudo docker-compose pull
          sudo docker-compose down || true
          sudo docker-compose up --build -d
        EOF

    - name: Cleanup private key file
      run: rm -f private_key.pem
